### PR TITLE
fix(utils/normalizeFallback): correctly pass all `options` to the default fallback (`file-loader`)

### LINKED ISSUE #138: v1.1.0 options.name is failure
This is my configuration file

```
{
                test: /\.(png|jpe?g|gif|svg)(\?.*)?$/,
                use: [
                    {
                        loader: 'url-loader',
                        options: {
                            name: 'img/[name].[hash:7].[ext]',
                            limit: 8192
                        }
                    }
                ]
            },
```

This is the generated file

image

v1.0.1 is ok

image

### PR DESCRIPTION
**Pull request by insin**
This PR contains a:

- [x] **bugfix**
- [ ] new **feature**
- [ ] **code refactor**
- [ ] **test update** 
- [ ] **typo fix**
- [ ] **metadata update**

### Motivation / Use-Case

Fixes #138 by passing on all non-`url-loader` options when defaulting to `file-loader` as the fallback.

This also implements the suggestion which was previously in a code comment to strip out url-loader specific options when passing them to the fallback - this shouldn't be a breaking change as they were never accepted by `file-loader`.

### Breaking Changes

Should undo a breaking change for people who depended on options being passed on to `file-loader` 😹 

### Additional Info

❤️

### CODE REVIEW

**Comment by evilebottnawi** [comment]
Wait review and we will release

File: src/utils/normalizeFallback.js [hunk 1]
```diff
@@ -7,12 +7,18 @@ function normalizeFallbackString(fallbackString, originalOptions) {
...
-  // Perhaps it would make sense to strip out ‒ or "consume" ‒ the options we know were meant for url-loader: limit and
-  // mimetype.
+  // To remain consistent with version 1.0.1, pass any other options which were provided to url-loader to the fallback loader.
+  const { fallback, limit, mimetype, ...otherOptions } = originalOptions;
+
+  if (Object.keys(otherOptions).length === 0) {
+    return {
+      loader: fallbackString,
+    };
+  }
```
Comment (evilebottnawi) [inline src/utils/normalizeFallback.js]: We really need in this? Looks better always return `query`.

**Comment by michael-ciniawsky** [comment]
The `utils/normalizeFallback` code is really wierd imho, I personally think It should not have been landed in that way tbh :)

**Comment by zhangyuheng** [comment]
@evilebottnawi can you publish a new version

**Comment by michael-ciniawsky** [comment]
Released in [`v1.1.2`](https://github.com/webpack-contrib/url-loader/releases/tag/v1.1.2) 🎉
